export const HISTORICAL_CASES = {
  THREE_MILE_ISLAND: {
    id: 'THREE_MILE_ISLAND',
    name: 'Three Mile Island',
    year: 1979,
    location: 'Pensilvania, EE.UU.',
    reactor: 'PWR — Babcock & Wilcox',
    what: 'Una válvula de alivio de presión (PORV) quedó atascada abierta tras un pico transitorio. El indicador en sala de control mostraba "cerrada" (estado de la señal eléctrica, no de la válvula). El refrigerante se escapó durante más de dos horas sin que los operadores lo detectaran.',
    consequence: 'Fusión parcial del núcleo. No hubo víctimas directas, pero se liberó una pequeña cantidad de gas radiactivo.',
    lesson: 'Los cambios rápidos sin monitoreo sistemático causan pérdida de situational awareness. Los instrumentos muestran lo que miden, no necesariamente lo que ocurre físicamente.',
    casualties: 0,
    scale: 'INES 5 — Accidente con consecuencias externas limitadas',
    color: 'yellow',
    emoji: '⚛️',
  },

  FUKUSHIMA: {
    id: 'FUKUSHIMA',
    name: 'Fukushima Daiichi',
    year: 2011,
    location: 'Fukushima, Japón',
    reactor: 'BWR — General Electric Mark I',
    what: 'El terremoto M9.0 activó el SCRAM automático correctamente en los tres reactores. El tsunami posterior (14 m) inundó y destruyó todos los generadores diesel de emergencia. Sin electricidad, las bombas de refrigeración se detuvieron. El calor residual de fisión continuó durante horas sin enfriamiento activo.',
    consequence: 'Fusión de combustible en unidades 1, 2 y 3. Explosiones de hidrógeno en edificios de contención. Liberación significativa de Cs-137 e I-131.',
    lesson: 'El calor residual persiste horas después de la parada. Un reactor "apagado" sigue necesitando refrigeración activa durante días. Los sistemas de seguridad de última línea no deben depender de una sola fuente de energía.',
    casualties: 1,
    scale: 'INES 7 — Accidente mayor (misma escala que Chernobyl)',
    color: 'blue',
    emoji: '🌊',
  },

  CHERNOBYL: {
    id: 'CHERNOBYL',
    name: 'Chernobyl Unidad 4',
    year: 1986,
    location: 'Prípiat, Ucrania (URSS)',
    reactor: 'RBMK-1000 — grafito/agua',
    what: 'Para una prueba de turbina, los operadores deshabilitaron los sistemas de protección automática y redujeron la potencia a ~200 MW (nivel inestable para el RBMK). El reactor tenía coeficiente de vacío positivo: al formarse burbujas de vapor, la reactividad aumentaba. Al intentar el SCRAM, las barras con punta de grafito aumentaron brevemente la reactividad antes de absorber neutrones.',
    consequence: 'Explosión de vapor y destrucción del reactor. Incendio de grafito durante 10 días. 31 muertes directas. Zona de exclusión de 30 km.',
    lesson: 'Nunca deshabilitar sistemas de seguridad bajo ninguna circunstancia operacional. Un reactor con retroalimentación positiva es inherentemente inestable. Los procedimientos existen porque alguien murió antes de escribirlos.',
    casualties: 31,
    scale: 'INES 7 — Accidente mayor',
    color: 'red',
    emoji: '💣',
  },
};
